version: '3.8'

volumes:
  db-store:
networks:
  network-app:
    driver: bridge

services: 
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jlpt_website
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - db-store:/var/lib/mysql
    networks:
      - network-app
  app:
    container_name: app-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - network-app
  nginx:
    container_name: nginx-service
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9001:80
    networks:
      - network-app
    depends_on:
      - app